<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

# Neural Networks

## *Data Science Unit 4 Sprint 2 Assignment 1*

## Define the Following:
You can add image, diagrams, whatever you need to ensure that you understand the concepts below.

### Input Layer: The input layer is the beginning/first layer of the network. Our data interacts directly with this layer - from this layer the data goes to the next layer where it will be processed by weights or functions.
### Hidden Layer: The hidden layer is between the input/output layers. They receive weighted inputs from the previous layers and generate output through an activation function.
### Output Layer: After data has been weighted, and activated the output layer transfers that info to be presented."Output layer neurons are the last actor nodes on the network".
### Neuron: Also called a node - it is the basic building block of a neural network and of the various layers.
### Weight: Each connection between nodes has a weight associated with it. Adjusting the wieghts are essential to training the network to decrease error. A weight decides how much influence the input will have on the output.
### Activation Function: Used to bring in non-linearity to a neural network. Determine the output of a model, accuracy, and efficiency.
### Node Map: Visual representation of the neural network architecture - flow of data, number of layers etc.
### Perceptron: A matehmatical model of a neuron. In the bio neuron the dendrite receives electrical signals from the axons of other neurons, but in the perceptron those electrical signals are rerpesented by numbers.


## Inputs -> Outputs

### Explain the flow of information through a neural network from inputs to outputs. Be sure to include: inputs, weights, bias, and activation functions. How does it all flow from beginning to end?

Data is received by the input layer and passed on to subsequent neurons. These neurons in the next layer are multiplied by a weight which determines the connection between the two neurons and then add up the value of every neuron it is connected to from the previous column. A bias value may be added at this point - to the total value. After all that math is completed the neuron applies the activation function. The activation function aims to limit the value and usually turns the total value calculated before to a number between 0 and 1 (sigmoid function).

## Write your own perceptron code that can correctly classify (99.0% accuracy) a NAND gate. 

| x1 | x2 | y |
|----|----|---|
| 0  | 0  | 1 |
| 1  | 0  | 1 |
| 0  | 1  | 1 |
| 1  | 1  | 0 |

In [5]:
import pandas as pd
data = { 'x1': [0,1,0,1],
         'x2': [0,0,1,1],
         'y':  [1,1,1,0]
       }

df = pd.DataFrame.from_dict(data).astype('int')

In [2]:
##### Your Code Here #####
import numpy as np
np.random.seed(555)

In [3]:
weights = np.random.random((2,1))

In [54]:
weights

array([[0.68638004],
       [0.58120733]])

In [6]:
dfnp = df.to_numpy()

In [33]:
dfnp

array([[0, 0, 1],
       [1, 0, 1],
       [0, 1, 1],
       [1, 1, 0]])

In [7]:
inputs = dfnp[:, 0:2]
inputs

array([[0, 0],
       [1, 0],
       [0, 1],
       [1, 1]])

In [15]:
correct_outputs = dfnp[:, 2]
correct_outputs = [[1],[1],[1],[0]]

In [5]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    sx = sigmoid(x)
    return sx * (1-sx)

In [108]:
weighted_sum = np.dot(inputs, weights)
weighted_sum


array([[0.        ],
       [0.62719546],
       [0.52994519],
       [1.15714066]])

In [109]:
activated_output = sigmoid(weighted_sum)
activated_output

array([[0.5       ],
       [0.65185327],
       [0.62947033],
       [0.76081277]])

In [110]:
error = correct_outputs - activated_output

In [111]:
error

array([[ 0.5       ],
       [ 0.34814673],
       [ 0.37052967],
       [-0.76081277]])

In [112]:
adjustments = error * sigmoid_derivative(weighted_sum)

In [60]:
inputs.T

array([[0, 1, 0, 1],
       [0, 0, 1, 1]])

In [61]:
adjustments

array([[ 0.125     ,  0.125     ,  0.125     , -0.125     ],
       [ 0.0745759 ,  0.0745759 ,  0.0745759 , -0.14814589],
       [ 0.08249834,  0.08249834,  0.08249834, -0.14752321],
       [ 0.03765491,  0.03765491,  0.03765491, -0.13376048]])

In [113]:
weights += np.dot(inputs.T, adjustments)
weights

array([[0.56775389],
       [0.47791639]])

In [17]:
# Update our weights 10,000 times - (fingers crossed that this process reduces error)

def unnamed_function(inputs, weights, correct_ouputs):
    
    for iteration in range(10000):

        # Weighted sum of inputs / weights
        weighted_sum = np.dot(inputs, weights)
        
        activated_output = 1 / (1 + np.exp(-weighted_sum))

        # Cac error
        error = correct_outputs - activated_output
        
        sigmoid_derivative = activated_output * (1-activated_output)

        adjustments = error * sigmoid_derivative

        # Update the Weights
        weights += np.dot(inputs.T, adjustments)

    print("Weights after training")
    print(weights)

    print("Output after training")
    print(activated_output)

In [18]:
unnamed_function(inputs, weights, correct_outputs)

Weights after training
[[ 1.38777878e-16]
 [-3.05311332e-16]]
Output after training
[[0.5]
 [0.5]
 [0.5]
 [0.5]]


## Implement your own Perceptron Class and use it to classify a binary dataset: 
- [The Pima Indians Diabetes dataset](https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv) 

You may need to search for other's implementations in order to get inspiration for your own. There are *lots* of perceptron implementations on the internet with varying levels of sophistication and complexity. Whatever your approach, make sure you understand **every** line of your implementation and what its purpose is.

In [78]:
diabetes = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv')
diabetes.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

Although neural networks can handle non-normalized data, scaling or normalizing your data will improve your neural network's learning speed. Try to apply the sklearn `MinMaxScaler` or `Normalizer` to your diabetes dataset. 

In [95]:
from sklearn.preprocessing import MinMaxScaler, Normalizer

feats = list(diabetes)[:-1]

x = diabetes.values #returns a numpy array
min_max_scaler = MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
df = pd.DataFrame(x_scaled, columns = diabetes.columns)

In [96]:
feats

['Pregnancies',
 'Glucose',
 'BloodPressure',
 'SkinThickness',
 'Insulin',
 'BMI',
 'DiabetesPedigreeFunction',
 'Age']

In [99]:
y = df['Outcome']

In [100]:
y

0      1.0
1      0.0
2      1.0
3      0.0
4      1.0
      ... 
763    0.0
764    0.0
765    0.0
766    1.0
767    0.0
Name: Outcome, Length: 768, dtype: float64

In [101]:
X = df.drop('Outcome', axis=1)

In [106]:
##### Update this Class #####

class Perceptron:
    
    def __init__(self, rate = 0.01, niter = 10):
        self.rate = rate
        self.niter = niter
    
    def __sigmoid(self, x):
        return 1 / (1 + np.exp(-x))
    
    def __sigmoid_derivative(self, x):
        sx = sigmoid(x)
        return sx * (1-sx)
    
    def fit(self, X, y):
        """Fit training data
        X : Training vectors, X.shape : [#samples, #features]
        y : Target values, y.shape : [#samples]
        """

        # Randomly Initialize Weights
        self.weight = np.zeros(1 + X.shape[1])
        self.errors = []
        
        for i in range(self.niter):
          err = 0
          for xi, target in zip(X, y):
            delta_w = self.rate * (target - self.predict(xi))
            self.weight[1:] += delta_w * xi
            self.weight[0] += delta_w
            err += int(delta_w != 0.0)
          self.errors.append(err)
        return self


#     def predict(self, X):
        
#         return np.where(self.net_input(X) >= 0.0, 1, -1)

In [104]:
this = Perceptron()

In [107]:
this.fit(X,y)

AttributeError: 'Perceptron' object has no attribute 'net_input'

## Stretch Goals:

- Research "backpropagation" to learn how weights get updated in neural networks (tomorrow's lecture). 
- Implement a multi-layer perceptron. (for non-linearly separable classes)
- Try and implement your own backpropagation algorithm.
- What are the pros and cons of the different activation functions? How should you decide between them for the different layers of a neural network?